version: ~> 1.0
language: node_js
os:
 - linux
node_js:
 - "14"
 - "12"
 - "10"
install:
 - travis_wait 30 npm install --no-audit --ignore-scripts
before_script:
 - rm -f travis_wait_*.log
script:
 - npm run pretest
 - npm run tests-only
